services:
  core:
    extends:
      file: docker-compose.yml
      service: core
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '3000:3000'
      - '51820:51820/udp'
      - '51821:51821/tcp'
      - '9229:9229'

  wireguard-client:
    image: amneziavpn/amneziawg-go
    command: tail -f /dev/null
    volumes:
      - ./wg0.conf:/etc/amnezia/amneziawg/wg0.conf
