FROM node:22-slim
WORKDIR /app

RUN apt-get update && apt-get install -y wireguard iproute2 iptables nano

COPY package*.json ./
RUN npm ci && npm cache clean --force
ENV NODE_ENV=development
EXPOSE 3000 51820 9229

CMD ["npm", "run", "start:debug"]