version: '3'
services:
  core:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./packages:/app/packages
      - ./package.json:/app/package.json
      - ./tsconfig.json:/app/tsconfig.json
    ports:
      - "3000:3000"
      - "9229:9229"
    command: npm run debug -w=packages/core
    environment:
      - NODE_ENV=development
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1