[Interface]
PrivateKey = kLYy9jJ7b/pmdGnoZ3m60Y/m2tYhG1kgUoF8+WvgoXk=
Address = 10.0.0.2/32
Jc = 4
Jmin = 40
Jmax = 70
S1=0
S2=0
H1=1
H2=2
H3=3
H4=4

[Peer]
PublicKey = SuuHhCgYfjjKB7m+4vq8GiIrUHD82NZkhj0vfoi27EQ=
Endpoint = 45.67.229.56:30500
AllowedIPs = 0.0.0.0/0 
PersistentKeepalive = 25