[Interface]
PrivateKey = <CLIENT_PRIVATE_KEY>
Address = 10.0.0.2
DNS = 8.8.8.8
Jc = 4
Jmin = 40
Jmax = 70
S1 = 0
S2 = 0
H1 = 1
H2 = 2
H3 = 3
H4 = 4

[Peer]
PublicKey = <SERVER_PUBLIC_KEY>
Endpoint = <SERVER_IP>:30500
AllowedIPs = 0.0.0.0/0
PersistentKeepalive = 25