name: Deploy to VPS

on:
  workflow_call:
    secrets:
      SSH_USERNAME:
        required: true
      SSH_PASSWORD:
        required: true
env:
  IMAGE_NAME: ecalcutin/tunnel

jobs:
  deploy-vps:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Copy docker-compose
        uses: appleboy/scp-action@master
        with:
          host: 45.67.229.235
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          source: 'docker-compose.yml'
          target: '~/'

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: 45.67.229.235
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Stop the application
            cd ~
            docker-compose down

            # Pull the latest image
            docker pull ecalcutin/tunnel:latest

            # Start the application
            docker-compose up -d

            # Clean up old images
            docker image prune -a -f --filter "until=24h"
